language: node_js
sudo: false
node_js:
  - stable
  - lts/*

env:
  global:
    - GK_LOCK_YARN_OPTS=--ignore-engines

cache:
  yarn: true
before_cache: rm -rf node_modules/.cache

before_install:
  - npm i -g greenkeeper-lockfile yarn
  - &prepKey if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
  - greenkeeper-lockfile-update

install: yarn install --ignore-engines

script: npm run lint && npm test

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

stages:
  - Test
  - Release

jobs:
  include:
    - stage: Release
      node_js: stable
      if: branch = master AND type = push AND (NOT tag IS present)
      before_install:
        - npm i -g yarn
        - *prepKey
      before_script: npm run build
      script: semantic-release
      after_script: []
      after_success: []
