language: node_js
sudo: false
node_js:
- stable
- lts/carbon
- lts/boron

cache:
  yarn: true
  directories:
  - node_modules
before_cache: rm -rf node_modules/.cache

before_install:
- npm i -g greenkeeper-lockfile yarn
- &prepKey if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
- greenkeeper-lockfile-update

install: yarn install --check-files

script: yarn run lint && yarn test

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;

stages:
- Test
- Release

jobs:
  include:
  - stage: Test
  - stage: Release
    node_js: stable
    if: branch = master AND type = push AND (NOT tag IS present)
    before_install: &bfiRelease
    - npm i -g yarn
    - *prepKey
    before_script: &bfsRelease yarn run build
    script: semantic-release
    after_script: []