base: &base
  language: node_js
  node_js: 9
  sudo: false
  cache:
    directories:
      - node_modules
  before_script: greenkeeper-lockfile-update
  before_cache: rm -rf ./node_modules/.cache
  after_success: cat ./coverage/lcov.info | coveralls
  before_deploy: npm run build
  script:
    - npm run lint
    - npm test

jobs:
  include:
    - <<: *base
      if: type IN (push, cron)
      env:
        - secure: "cSSf8X1L8kQo5Wsoy9UdtSY/tdKWCDyX8C+0F45E+BW+8wLkfWcWOzL0ztZOVXRbcbZote6U0I8YXbBsFpK738NVHrjt9bWaj4JHw43fXMg/1ynqEuIGTPAvMlctM++qXMw3txZKd02XEIISzhzH0M+7bZNJajBMtFvIx+JLpPd5XTgz5BsEkCCdX+uLOfFVdYEZGx3Rm/fSmkmspuDyBqVEKHX6Fj+AS8tHachR42V6eaGNySOU9loE8Dyc5KRhpY/son5l1e+cbbS9w49NPyAoH7YyFwEtOvaeZmTx7wI0RDUZ+76WYTdunfOJdVZ1R2lJN2STCcI4auvowlTin7SeOruw7BFqElgmMo9CbZUOjSK00pkLARRV44M0X48Ip+TZeucLkeBde0y3yOPnhupKCTusY0zVIZLqeXyarsJLyC9KP71XPGKB7/cz8gGgHasHBS55w9uB20nMQCJjyzloSholfF0pTkDFmkztq/Wf3LxyV0251bJ2OSodjEeJlrIEddR/2jrZx4X6S1FAPn2FlNdJngvLoN8DAK+eQrTnegqzAlp+eeN7K8EZQaXhyrg5JRUsrdLbUVj7UcXcvFnwTwup3Jt9ryIuzWz+5fKNwiWx7S1JKgX78Cjta5RrQbjYLW1B44QxFzGyAdhns+ChVkxhcxwfbjFT7JexCg8="
      after_script: if [ $GH_TOKEN ]; then greenkeeper-lockfile-upload; fi;
      deploy:
          provider: npm
          skip_cleanup: true
          email: a.molcanovas@gmail.com
          api_key:
            secure: lLnzdAIdzZ5qLt7S3YtydSWYIkvgoBQ1PVaFCdIBgAl2tYaffAcOOwStkayZm4gUhw4/JZKGq1wLiiQFxgyLqo8Rsun+L4aGem4iSL1LgPiz4w2xHdbF4bvDG8DDHCVUWNgVb1r/oVQHAYTJPRhpHnY1Z3CNbWyjs553G/oZ10Ml271FMTtgVof4Pg5HAOBbO1rneO5PZKWscr/pPC7sy2qp56WRago9IdXpt9qeWYTeKgS/QT+Yh+so4U6r6+2g+qiam5VQcMs+cbcWG2GkG/XXkDsKyg0w8tsyt5tEYZ4fyRDJA31ZdJeG9tGHRs+sAo97FkBKU8qqugJhLvj5VTlvcpT5onEC7kUre51WYYqB6E/UdHCLmZATwPSaFMJX+2916mVp5rC2JqgW0wOCj4NUmRaPfAps4+JvhuT5PYX5PVHZ891wQLsRPyzsvM1ohlQOCoLoIpMeJPix93pqAWXEPLmyyiJ6VW3VTQzqvtJIybD+gvYgCtvrm7Ucjk9XBsElgToS8p4FF07yOi+Pk70PRm9NPbvR/f+v0QWGgcf+n5cV51LDMWK3OFZ/Nym3nEpEfGKZPqq+m5m0r74/770dfLhZ6RyrtL/O3l4LLswdtSHUJOxmZ5n+Y99+mOuY5BKsQpBdfBTymyy24I4V7sUg4l9+STUtBjSYD7eI8nw=
          on:
            tags: true
    - <<: *base
      if: NOT type IN (push, cron)
